name: Lint, test and deploy
on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch:  
  push:
    branches:
      - main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feature/**' # feature/add-page-1  feature/add-button
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci 
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy
        run: echo "Deploying"